### PR TITLE
fix(http-client): call trackRequestEnd when fetch fails

### LINKED ISSUE #119: call trackRequestEnd when fetch fails
**I'm submitting a bug report**

* **Library Version:**
1.7.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.14

* **Node Version:**
6.10.0

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
webpack 4

* **Browser:**
Chrome 71

* **Language:**
TypeScript 2.6.1

**Current behavior:**
I'm using the `isRequesting` observable property of fetch-client to provide user feedback in my app when a request is in progress. It works well, except when the server I'm trying to reach with fetch-client is down. Then, the fetch-client rejects the request with "Failed to fetch" error but do not set `isRequesting` to false.

**Expected/desired behavior:**

* **What is the expected behavior?**

When the request fails, I think `isRequesting` must be set accordingly

* **What is the motivation / use case for changing the behavior?**

The goal of `isRequesting` is to know if a request is in progress. If the requests fails, it's not in progress anymore.

**My attempt to fix this**

I'm assuming that the `trackRequestEnd` is not called when fetch rejects. I've tried to fork the code and build the fetch-client library but for some reason I'm not successful at building the code. I provide here my supposed fix for this scenario, if anybody can help out with building / testing this, it would be great.

https://github.com/ben-girardet/fetch-client/commit/380a47c3967a3139fcdf7d35044f908dea50f9ef

### PR DESCRIPTION
**Pull request by ben-girardet**
@huochunpeng @bigopon 

Here is my PR to fix #119 

I've also extended test coverage regarding the isRequesting property. Two of the new tests failed before the fix and pass now.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Nice @ben-girardet Thanks for working on this, complete with tests. @huochunpeng @bigopon This seems pretty straight forward. Have I missed anything? 2nd pair of eyes appreciated and we can get this in today and out with the next batch of releases.

File: src/http-client.ts [hunk 1]
```diff
@@ -141,10 +141,17 @@ export class HttpClient {
       })
       .then(result => {
         if (Request.prototype.isPrototypeOf(result)) {
-          return this.fetch(result);
+          let recursiveFetch = this.fetch(result);
+          trackRequestEnd(this);
+          return recursiveFetch;
         }
+        return Promise.resolve(result);
+      }).then((result) => {
```
Comment (bigopon) [inline src/http-client.ts]: I think it would better be:

```ts
.then(
  result => {
    trackRequestEnd(this);
    return result
  },
  error => {
    trackRequestEnd(this);
    throw / promise reject ... error
  }
)
```

**Comment by bigopon** [comment]
@ben-girardet @EisenbergEffect 

I think the suggestion from @huochunpeng 

```js
.then(
  result => {
        if (Request.prototype.isPrototypeOf(result)) {
// this recursive fetch call might already triggered trackRequestEnd in an error catch
// you don't want to process the error again that triggers another trackRequestEnd
          return this.fetch(result);
        }
        this::trackRequestEnd();
        return result;
  },
  error => {
    this::trackRequestEnd();
    return Promise.reject(error);
  }
);
```

Is quite proper fix for this, as the current fix seems to cause imbalanced values.

**Comment by huochunpeng** [comment]
My previous suggestion is based on my limited understanding. I am still confused about the pair of trackRequestEnd.

If you check my original question, it seems there is an unpaired trackRequestStart.

**Comment by ben-girardet** [comment]
@huochunpeng you're right, there is still a potential issue with the recursive fetch. My understanding is probably not better than yours to be honest so I'm not sure the way to go from here.

By giving another look I suggest a change to my previous fix, see below the code with comment to describe my thinking.

```js
  fetch(input: Request|string, init?: RequestInit): Promise<Response> {
    trackRequestStart(this); // (1) start tracking each fetch

    let request = this.buildRequest(input, init);
    return processRequest(request, this.interceptors, this)
      .then(result => {
        let response = null;

        if (Response.prototype.isPrototypeOf(result)) {
          response = Promise.resolve(result);
        } else if (Request.prototype.isPrototypeOf(result)) {
          request = result;
          response = fetch(result);
        } else {
          // tslint:disable-next-line:max-line-length
          throw new Error(`An invalid result was returned by the interceptor chain. Expected a Request or Response instance, but got [${result}]`);
        }
        return processResponse(response, this.interceptors, request, this);
        // (2) at this point we either return a Promise or throw an Error, which means we end up either in (3) or (7)
      })
      .then(result => {
        // (3) At that point the tracking is still in progress for sure
        if (Request.prototype.isPrototypeOf(result)) {
          // (4) This is where I'm not sure what is happening 
          // In fact I haven't been able to write a test that go through this portion of code
          // but still my thinking was:
          // 
          // - by calling this.fetch, there is a recursive call to (1) that will create a new
          //    pair of tracking start/end
          // - because of this, it's important to make sure that the original pair will be ended too
          // - for this to happen, we need to make sure that the original fetch call still go through 
          //    trackRequestEnd
          // - this will be the case if we return a Promise or throw an error
          // - and it's precisely the result of this.fetch
          //
          // so I suggest to keep the original code that was:
          return this.fetch(result);
        }
        return Promise.resolve(result);
        // (5) at this point we either return 
        // - the result from this.fetch with the recursive call in (4)
        // - or the restful of Promise.resolve(result)
        // so se will end up either in the following then (6) or catch (7)
      }).then((result) => {
        // (6) end tracking for Promise that resolve
        trackRequestEnd(this);
        return result
      }).catch((error) => {
        // (7) end tracking for Promise that rejects
        trackRequestEnd(this);
        return Promise.reject(error); // forward to error for another catch in the code using client.fetch()
      });
  }
```

**Comment by ben-girardet** [comment]
Which, in summary, seems to me the same than @huochunpeng suggestion.

Therefore I've updated my PR with his code.

**Comment by huochunpeng** [comment]
My suspicion is correct. Apart from this issue, the existing code **DOES have an unpaired trackRequestStart**.

Existing code on master branch.

```js
fetch(input: Request|string, init?: RequestInit): Promise<Response> {
  trackRequestStart(this); // this could be unpaired.

  let request = this.buildRequest(input, init);
  return processRequest(request, this.interceptors, this)
    .then(result => {
      // ...
    })
    .then(result => {
      if (Request.prototype.isPrototypeOf(result)) {
        // as far as I understand, this recursive fetch is called when
        // RetryInterceptor decided to issue another same request.
        // this recurisve fetch (assume it will succeed) will call a pair
        // of trackRequestStart and trackRequestEnd.
        return this.fetch(result);
      }
      // When the recurisve fetch did its thing,
      // This outer trackRequestEnd is missed!
      trackRequestEnd(this);
      return result;
    });
}
```

This can be easily verified by adding test coverage for isRequesting to retry-interceptor.
`test/http-client.spec.ts` line 392
```js
    it('forward requests', (done) => {
      const path = 'retry';
      let retry = 3;
      fetch.and.returnValue(Promise.reject(new Response(null, { status: 500 })));
      let interceptor: Interceptor = {
        response(r) { return r; },
        responseError(r) {
          if (retry--) {
            let request = client.buildRequest(path);
            return request;
          } else {
            throw r;
          }
        }
      };
      spyOn(interceptor, 'response').and.callThrough();
      spyOn(interceptor, 'responseError').and.callThrough();

      client.interceptors.push(interceptor);

      // add check before fetch, this one passes.
      expect(client.isRequesting).toBe(false);

      client.fetch(path)
        .catch(() => {
          expect(interceptor.response).not.toHaveBeenCalled();
          expect(interceptor.responseError).toHaveBeenCalledWith(jasmine.any(Response), jasmine.any(Request), client);
          expect(fetch).toHaveBeenCalledTimes(4);
          expect(client.activeRequestCount).toBe(0);
          // add check after fetch, this one fails!
          // client.activeRequestCount is 4 here! not 0.
          console.log('client.activeRequestCount = ' + client.activeRequestCount);
          expect(client.isRequesting).toBe(false);
          done();
        });
    });
```

Test result on existing code on master branch.
```
START:
LOG: 'client.activeRequestCount = 4'
  HttpClient
    interceptors
      ✖ forward requests

Finished in 0.069 secs / 0.004 secs @ 08:40:44 GMT+1100 (AEDT)

SUMMARY:
✔ 0 tests completed
ℹ 53 tests skipped
✖ 1 test failed

FAILED TESTS:
      ✖ forward requests
        HeadlessChrome 71.0.3578 (Mac OS X 10.14.2)
      Error: Expected true to be false.
          at <Jasmine>
          at client.fetch.catch (webpack:///test/http-client.spec.ts:422:38 <- test/http-client.spec.js:2626:45)
```

**Comment by huochunpeng** [comment]
The code in 
https://github.com/aurelia/fetch-client/pull/121#issuecomment-455085119 is the correct fix.

To clean it up
```ts
  fetch(input: Request|string, init?: RequestInit): Promise<Response> {
    trackRequestStart(this);

    let request = this.buildRequest(input, init);
    return processRequest(request, this.interceptors, this)
      .then(result => {
        let response = null;

        if (Response.prototype.isPrototypeOf(result)) {
          response = Promise.resolve(result);
        } else if (Request.prototype.isPrototypeOf(result)) {
          request = result;
          response = fetch(result);
        } else {
          // tslint:disable-next-line:max-line-length
          throw new Error(`An invalid result was returned by the interceptor chain. Expected a Request or Response instance, but got [${result}]`);
        }

        return processResponse(response, this.interceptors, request, this);
      })
      .then(result => {
        if (Request.prototype.isPrototypeOf(result)) {
          return this.fetch(result);
        }
        return result;
      })
      .then(
        result => {
          trackRequestEnd(this);
          return result;
        },
        error => {
          trackRequestEnd(this);
          throw error;
        }
      );
  }
```

Also need to add test coverage for `activeRequestCount` and `isRequesting` (both are public interface on HttpClient) in most tests of `http-client.spec.ts`.

**Comment by huochunpeng** [comment]
The RetryInterceptor is an opt-in for end users in configure. I believe most of end users did not turn it on, that's why nobody complains so far.

**Comment by EisenbergEffect** [comment]
@huochunpeng So, we should be good to go on this, correct?

**Comment by huochunpeng** [comment]
Wait for @ben-girardet to update the code and tests.

**Comment by EisenbergEffect** [comment]
Ok, I just realized I wasn't properly following the conversation. As soon as we get that, I can release this. I'll have time slated to release this tomorrow, if we can get it in by then ;)

**Comment by huochunpeng** [comment]
@ben-girardet FYI, inside promise chain (then or catch), you don't need to do `Promise.resolve` or `Promise.reject` wrapping for any value or error.

The `then` or `catch` method automatically wrap the return value in `Promise.resolve`. If you just do `throw` inside them, they will catch it and return a `Promise.reject` for you. You don't have to do any double work.

**Comment by ben-girardet** [comment]
Thanks @huochunpeng !!

Good catch on the unpaired trackRequestStart and test coverage for activeRequestCount. I've updated the PR with your solution, including your new test.

Ready for another review @EisenbergEffect
