### PR TITLE
fix(util): Discontinue using Blob for JSON

### LINKED ISSUE #90: Question - json()'s benefit of converting to Blob
## Question:

What is the benefit of the `json()` method converting an object to a blob, rather than just sending the stringified object?  I am _pretty sure_ this is what causes the request body to not show up in the chrome devtools.

For example:

image

This is a POST ^ but I can't see the body unless I use something like Fiddler, which is less convenient.

### PR DESCRIPTION
**Pull request by davismj**
Blobs obscure the JSON in Chrome dev tools, etc., and so we will stop using them for JSON.

Closes #90

### CODE REVIEW

**Comment by davismj** [comment]
@bigopon @bryanrsmith @EisenbergEffect review?

**Comment by EisenbergEffect** [comment]
@davismj It's fine with me as long as this doesn't break people's production apps. If it can cause a break, then we should do a major version change. If we do that, we should consider if there's anything else that we want to break, so we don't create too much churn. If it's not breaking, then no big deal. It makes sense to me.

**Comment by davismj** [comment]
I believe this is non-breaking, but I'd like a second pair of eyes on it in case I'm wrong.

**Comment by EisenbergEffect** [comment]
Looks good. @davismj Feel free to merge.

File: src/http-client.js [hunk 1]
```diff
@@ -43,6 +43,11 @@ export class HttpClient {
     if (typeof fetch === 'undefined') {
       throw new Error('HttpClient requires a Fetch API implementation, but the current environment doesn\'t support it. You may need to load a polyfill such as https://github.com/github/fetch');
     }
+
+    // Use application/json as the default content-type.
+    this.defaults = {
+      headers: { 'content-type': 'application/json' }
```
Comment (gheoan) [inline src/http-client.js]: @davismj This does not play well with CORS. Some API endpoints do not accept the `content-type` header on requests. Got a CORS error after upgrading to the version that includes this.

Comment (davismj) [reply src/http-client.js]: Hm. I'm thinking that is the right thing to do anyway, and that the problem isn't the library but your CORS configuration. However, I think you're right that maybe we need to only add the header when the post has a body. 

In any case, if you're posting with a body to a cross domain API, you'd really want to respond with content-type in your Access-Control-Allow-Headers list, and if it was working before, it was more of a coincidence.

Don't you think?
